// Testdata för lokal utveckling. Används bara när import.meta.env.DEV är true.
export const devSeed = {
  general: {
    name: "Anna Johansson",
    personalNumber: "8504121234",
    consultationDate: "2026-06-15",
    gender: "female",
    height: "168",
    weight: "63",
    address: "Storgatan 12, 411 38 Göteborg",
    occupation: "Sjuksköterska",
    phone: "0701234567",
    notes: "Söker för kronisk trötthet och magbesvär. Har haft symptomen i ungefär två år.",
  },
  medical: {
    familyHistory: "yes",
    familyNotes: "Mamma har typ 2-diabetes. Pappa har haft hjärtinfarkt. Tagit antibiotika 3 gånger senaste 5 åren.",
    medicines: ["dietary-supplements"],
    medicinesList: [
      { productName: "D-vitamin", dosage: "2000 IE/dag", duration: "6 månader" },
      { productName: "Magnesium", dosage: "300 mg/dag", duration: "3 månader" },
    ],
    otherTreatment: "no",
    otherTreatmentDetails: "",
  },
  diet1: {
    hasType: "true",
    hasTypeNotes: "Äter mestadels vegetariskt men äter fisk ett par gånger i veckan.",
    dietMealPattern: ["regular", "calmEating"],
    dietMealPatternNotes: "",
    dietFoodType: ["mostlyHomecooked"],
    dietFoodTypeNotes: "Lagar mat från grunden de flesta dagar.",
    fruits: "Banan och äpple, 1–2 frukter om dagen",
    vegetables: "Spenat, broccoli, morot – äter grönt varje dag",
    cookingMethods: ["boiled", "ovenBaked", "raw"],
    favoriteFoods: "Pasta, sushi, hemmagjord soppa",
    foodPositiveResponse: "Grönsaker och fisk",
    cravings: "Sötsaker, framför allt choklad på eftermiddagen",
    hardToGiveUp: "Kaffe och choklad",
    meatConsumption: "false",
    meatConsumptionType: [],
    meatFrequency: { beef: "", pork: "", poultry: "", game: "" },
    seafoodConsumption: "weekly",
    seafoodConsumptionType: ["salmon", "whiteFish"],
    seafoodFrequency: {
      salmon: "weekly",
      whiteFish: "monthly",
      oilyFish: "",
      tuna: "",
      otherFish: "",
      shrimp: "",
      mussels: "",
      crustaceans: "",
      otherSeafood: "",
    },
    otherSeafoodNotes: "",
    seafoodMethods: ["frozen"],
    seafoodWeeklyPortions: "3",
  },
  diet2: {
    wheatFrequency: "weekly",
    dairyFrequency: "weekly",
    sugarFrequency: "weekly",
    caffeineFrequency: "daily",
    fastFood: {
      pizza: "monthly",
      kebabFalafel: "false",
      streetFood: "false",
      burger: "false",
      readyMeals: "seldom",
    },
    foodReactions: ["dairy", "sugar"],
    foodReactionSymptoms: "Gaser och uppsvälld mage av mejeriprodukter. Trött och okoncentrerad av socker.",
    sugarFriedProducts: ["chocolate", "cookies", "iceCream"],
    sugarFriedOther: "",
    sugarFriedFrequency: "weekly",
    drinksAlcohol: "true",
    alcoholPreference: ["wine"],
    alcoholWeekly: "1–2 glas vin i veckan",
    allergies: "Lätt känslig för pollen, inga kända livsmedelsallergier.",
  },
  lifestyle1: {
    travelFrequency: "rarely",
    countriesVisited: "Spanien (2024), Thailand (2023), Danmark (2022)",
    travelIllness: "Fick maginfluensa i Thailand 2023, varade i 4 dagar.",
    workSatisfaction: "good",
    workStress: "high",
    workload: "heavy",
    hasChildren: "true",
    familyWellbeing: "veryGood",
    exercises: "true",
    exerciseFrequency: "Löpning 2ggr/veckan, styrketräning 1ggr/veckan",
    exerciseType: "Löpning och yoga",
    meditates: "true",
    meditationType: "Mindfulness 10–15 min, 3–4 gånger i veckan",
    doesYoga: "true",
    yogaType: "Hatha yoga, 1 gång i veckan",
    tobacco: ["false"],
    tobaccoAmount: "",
  },
  lifestyle2: {
    sleepQuality: ["lightSleeper", "wakesDuringNight"],
    sleepOnset: ["easyToSleep"],
    bedtimeWeekdays: "23:00",
    waketimeWeekdays: "06:30",
    bedtimeWeekends: "00:00",
    waketimeWeekends: "08:30",
    energyPeak: "forenoon",
    energyLow: "afternoon",
    phoneInMorning: "true",
    phoneShutdownTime: "22:00",
    phoneImpact: "Ja, jag scrollar istället för att vara närvarande med familjen på kvällen.",
    outdoors60min: "false",
    cognitiveSymptoms: ["goodMemory", "hardFocus"],
    breathing: ["fastBreathing"],
    calmBreathingTrigger: "Promenader i naturen och djupandningsövningar.",
    emotions: ["moodSwings", "worried", "anxiety"],
    immuneSystem: ["easyColds"],
    immuneNotes: "Brukar få 3–4 förkylningar per år.",
  },
  symptoms: {
    digestiveSymptoms: ["gas", "bloated", "nausea"],
    digestiveTiming: ["afterMeal", "heavyMeal"],
    digestiveTriggers: "Stress och oregelbundna mattider",
    digestiveAfterFood: "Gluten och mejeriprodukter verkar göra det värre",
    stoolConsistency: ["soft", "loose"],
    bowelFrequency: "1 gång per dag, ibland varannan dag",
    menstruationLength: "long",
    menstruationRegularity: "regular",
    bleedingDescription: "Måttlig, 5–6 dagar",
    cycleLength: "28 dagar",
    pmsSymptoms: ["tearful", "sugarCraving"],
    menopauseSymptoms: [],
    contraceptives: "Kopparspiral",
    otherHormonalSymptoms: "Ibland sömnstörningar kopplade till menscykeln",
    jointSymptoms: ["stiffness"],
    jointLocation: "Knän och höfter, framför allt på morgonen",
    jointOther: "Stelheten brukar försvinna efter 30 min rörelse",
    muscleSymptoms: ["soreness", "cramps"],
    muscleLocation: "Nacke, axlar och vader",
    muscleOther: "Kramperna är vanligast på natten i vaderna",
    circulationSymptoms: ["handsCold"],
    circulationOther: "Händerna är kalla framför allt vintertid",
    dentalFillings: ["plastic", "porcelain"],
    dentalIssues: ["teethGrinding"],
    skinSymptoms: ["dry", "easilyBruised"],
    skinLocation: "Armar och ben",
    currentEmotionalState: "Jag känner mig trött och lite nedstämd. Balansen mellan jobb och familj är svår just nu.",
    heartDesire: "Jag önskar mer energi och ro. Vill känna mig frisk och stark igen.",
    otherInfo: "Jag är väldigt motiverad och redo att göra förändringar i livsstilen.",
    motivation: "Mycket hög – jag vill verkligen må bättre och har prövat mycket på egen hand.",
    improvementGoals: "Energi, sömn och magtarmproblemen. Vill också lära mig hantera stress bättre.",
  },
};
