import Step01General from "../steps/Step01General";
import Step02Medical from "../steps/Step02Medical";
import Step03Diet01 from "../steps/Step03Diet01";
import Step04Diet02 from "../steps/Step04Diet02";
import Step05Lifestyle01 from "../steps/Step05Lifestyle01";
import Step06Lifestyle02 from "../steps/Step06Lifestyle02";
import Step07Symptoms from "../steps/Step07Symptoms";
import Step08Review from "../steps/Step08Review";

export const steps = [
  {
    id: "general",
    title: "Allmänna uppgifter",
    component: Step01General,
    fields: [
      "general.name",
      "general.personalNumber",
      "general.consultationDate",
      "general.height",
      "general.weight",
      "general.gender",
      "general.address",
      "general.occupation",
      "general.phone",
      "general.notes",
    ],
    defaultValues: {
      general: {
        name: "",
        gender: "",
        consultationDate: "",
        address: "",
        occupation: "",
        phone: "",
        height: "",
        weight: "",
        personalNumber: "",
        notes: "",
      },
    },
  },
  {
    id: "medical",
    title: "Medicinsk bakgrund",
    component: Step02Medical,
    fields: [
      "medical.familyHistory",
      "medical.medicines",
      "medical.medicinesList",
      "medical.otherTreatment",
      "medical.otherTreatmentDetails",
    ],
    defaultValues: {
      medical: {
        familyHistory: "",
        familyNotes: "",
        medicines: [],
        medicinesList: [{ productName: "", dosage: "", duration: "" }],
        otherTreatment: "",
        otherTreatmentDetails: "",
      },
    },
  },
  {
    id: "diet1",
    title: "Kosthållning – del 1/2",
    component: Step03Diet01,
    fields: [
      "diet1.hasType",
      "diet1.hasTypeNotes",
      "diet1.dietMealPattern",
      "diet1.dietMealPatternNotes",
      "diet1.dietFoodType",
      "diet1.dietFoodTypeNotes",
      "diet1.fruits",
      "diet1.vegetables",
      "diet1.cookingMethods",
      "diet1.favoriteFoods",
      "diet1.foodPositiveResponse",
      "diet1.cravings",
      "diet1.hardToGiveUp",
      "diet1.meatConsumption",
      "diet1.meatConsumptionType",
      "diet1.meatFrequency.beef",
      "diet1.meatFrequency.pork",
      "diet1.meatFrequency.poultry",
      "diet1.meatFrequency.game",
      "diet1.seafoodConsumption",
      "diet1.seafoodConsumptionType",
      "diet1.seafoodFrequency.salmon",
      "diet1.seafoodFrequency.whiteFish",
      "diet1.seafoodFrequency.oilyFish",
      "diet1.seafoodFrequency.tuna",
      "diet1.seafoodFrequency.otherFish",
      "diet1.seafoodFrequency.shrimp",
      "diet1.seafoodFrequency.mussels",
      "diet1.seafoodFrequency.crustaceans",
      "diet1.seafoodFrequency.otherSeafood",
      "diet1.otherSeafoodNotes",
      "diet1.seafoodMethods",
      "diet1.seafoodWeeklyPortions",
    ],
    defaultValues: {
      diet1: {
        hasType: "",
        hasTypeNotes: "",
        dietMealPattern: [],
        dietMealPatternNotes: "",
        dietFoodType: [],
        dietFoodTypeNotes: "",
        fruits: "",
        vegetables: "",
        cookingMethods: [],
        favoriteFoods: "",
        foodPositiveResponse: "",
        cravings: "",
        hardToGiveUp: "",
        meatConsumption: "",
        meatConsumptionType: [],
        meatFrequency: {
          beef: 0,
          pork: 0,
          poultry: 0,
          game: 0,
        },
        seafoodConsumption: "",
        seafoodConsumptionType: [],
        seafoodFrequency: {
          salmon: 0,
          whiteFish: 0,
          oilyFish: 0,
          tuna: 0,
          otherFish: 0,
          shrimp: 0,
          mussels: 0,
          crustaceans: 0,
          otherSeafood: 0,
        },
        otherSeafoodNotes: "",
        seafoodMethods: [],
        seafoodWeeklyPortions: "",
      },
    },
  },
  {
    id: "diet2",
    title: "Kosthållning - del 2/2",
    component: Step04Diet02,
    fields: [
      "diet2.wheatFrequency",
      "diet2.dairyFrequency",
      "diet2.sugarFrequency",
      "diet2.caffeineFrequency",
      "diet2.fastFood.pizza",
      "diet2.fastFood.kebabFalafel",
      "diet2.fastFood.streetFood",
      "diet2.fastFood.burger",
      "diet2.fastFood.readyMeals",
      "diet2.foodReactions",
      "diet2.foodReactionSymptoms",
      "diet2.sugarFriedProducts",
      "diet2.sugarFriedOther",
      "diet2.sugarFriedFrequency",
      "diet2.drinksAlcohol",
      "diet2.alcoholPreference",
      "diet2.alcoholWeekly",
    ],
    defaultValues: {
      diet2: {
        wheatFrequency: "",
        dairyFrequency: "",
        sugarFrequency: "",
        caffeineFrequency: "",
        fastFood: {
          pizza: "",
          kebabFalafel: "",
          streetFood: "",
          burger: "",
          readyMeals: "",
        },
        foodReactions: [],
        foodReactionSymptoms: "",
        sugarFriedProducts: [],
        sugarFriedOther: "",
        sugarFriedFrequency: "",
        drinksAlcohol: "",
        alcoholPreference: "",
        alcoholWeekly: "",
        allergies: "",
      },
    },
  },
  {
    id: "lifestyle1",
    title: "Livsstil/Hälsa – del 1/2",
    component: Step05Lifestyle01,
    fields: [
      "lifestyle1.travelFrequency",
      "lifestyle1.workSatisfaction",
      "lifestyle1.workStress",
      "lifestyle1.workload",
      "lifestyle1.hasChildren",
      "lifestyle1.familyWellbeing",
      "lifestyle1.exercises",
      "lifestyle1.exerciseFrequency",
      "lifestyle1.exerciseType",
      "lifestyle1.meditates",
      "lifestyle1.meditationType",
      "lifestyle1.doesYoga",
      "lifestyle1.yogaType",
      "lifestyle1.tobacco",
      "lifestyle1.tobaccoAmount",
    ],
    defaultValues: {
      lifestyle1: {
        travelFrequency: "",
        countriesVisited: "",
        travelIllness: "",
        workSatisfaction: "",
        workStress: "",
        workload: "",
        hasChildren: "",
        familyWellbeing: "",
        exercises: "",
        exerciseFrequency: "",
        exerciseType: "",
        meditates: "",
        meditationType: "",
        doesYoga: "",
        yogaType: "",
        tobacco: [],
        tobaccoAmount: "",
      },
    },
  },
  {
    id: "lifestyle2",
    title: "Livsstil/Hälsa – del 2/2",
    component: Step06Lifestyle02,
    fields: [
      "lifestyle2.sleepQuality",
      "lifestyle2.sleepOnset",
      "lifestyle2.bedtimeWeekdays",
      "lifestyle2.waketimeWeekdays",
      "lifestyle2.bedtimeWeekends",
      "lifestyle2.waketimeWeekends",
      "lifestyle2.energyPeak",
      "lifestyle2.energyLow",
      "lifestyle2.phoneInMorning",
      "lifestyle2.outdoors60min",
      "lifestyle2.cognitiveSymptoms",
      "lifestyle2.breathing",
      "lifestyle2.emotions",
    ],
    defaultValues: {
      lifestyle2: {
        sleepQuality: [],
        sleepOnset: [],
        bedtimeWeekdays: "",
        waketimeWeekdays: "",
        bedtimeWeekends: "",
        waketimeWeekends: "",
        energyPeak: "",
        energyLow: "",
        phoneInMorning: "",
        phoneShutdownTime: "",
        phoneImpact: "",
        outdoors60min: "",
        cognitiveSymptoms: [],
        breathing: [],
        calmBreathingTrigger: "",
        emotions: [],
        immuneSystem: [],
        immuneNotes: "",
      },
    },
  },
  {
    id: "symptoms",
    title: "Symptom & Avslutning",
    component: Step07Symptoms,
    fields: [
      "symptoms.digestiveTiming",
      "symptoms.stoolConsistency",
      "symptoms.bowelFrequency",
      "symptoms.jointLocation",
      "symptoms.muscleLocation",
      "symptoms.skinLocation",
      "symptoms.currentEmotionalState",
      "symptoms.motivation",
      "symptoms.improvementGoals",
    ],
    defaultValues: {
      symptoms: {
        digestiveSymptoms: [],
        digestiveTiming: [],
        digestiveTriggers: "",
        digestiveAfterFood: "",
        stoolConsistency: [],
        bowelFrequency: "",
        menstruationLength: "",
        menstruationRegularity: "",
        bleedingDescription: "",
        cycleLength: "",
        pmsSymptoms: [],
        menopauseSymptoms: [],
        contraceptives: "",
        otherHormonalSymptoms: "",
        jointSymptoms: [],
        jointLocation: "",
        jointOther: "",
        muscleSymptoms: [],
        muscleLocation: "",
        muscleOther: "",
        circulationSymptoms: [],
        circulationOther: "",
        dentalFillings: [],
        dentalIssues: [],
        skinSymptoms: [],
        skinLocation: "",
        currentEmotionalState: "",
        heartDesire: "",
        otherInfo: "",
        motivation: "",
        improvementGoals: "",
      },
    },
  },
  {
    id: "review",
    title: "Granska formuläret",
    component: Step08Review,
    fields: [],
  },
];
